name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: configure-msbuild-env
        uses: microsoft/setup-msbuild@v1.0.2
      - name: build
        run: |
          msbuild UmamusumeStoryDataExtractor.sln -m -p:Configuration=Release;Platform=x64
      - name: prepare-package
        run: |
          mkdir package
          cp -r -force UmamusumeStoryDataExtractor/bin/Release/net6.0/* package/
          cp -r -force UmamusumeStoryDataExtractor/bin/Release/net6.0/* package/
      - uses: actions/upload-artifact@v2
        with:
          name: UmamusumeStoryDataExtractor
          path: package
